Project:
  name: Churn Predictor
  random_state: 42
  test_size: 0.3

data:
  raw_path: data/raw/Telco_customer_churn.xlsx
  interim_path: data/interim/telecom_clean.csv


features:
  target: Churn Value

  drop_columns:
    - 'Country' 
    - 'State'
    - 'Lat Long'
    - 'Churn Label'
    - 'Churn Reason'
    - 'Count'

  categorical_columns:
    - Gender
    - Senior Citizen
    - Partner
    - Dependents
    - Phone Service
    - Multiple Lines
    - Internet Service
    - Online Security
    - Online Backup
    - Device Protection
    - Tech Support
    - Streaming TV
    - Streaming Movies
    - Contract
    - Paperless Billing
    - Payment Method
    - City

  numerical_columns:
    - Tenure Months
    - Monthly Charges
    - Total Charges
    - Zip Code
    - Latitude
    - Longitude
  
  meta_cols:
    - CLTV
    - CustomerID


  engineering:
    drop_churn_score: true
    add_engagement_score: false
    add_tenure_group: false
    add_tenure_log: false
    add_contract_ordinal: false
    add_family_stability: false
    add_fiber_no_support: false
    add_support_gap_count: false
    add_payment_automatic_flag: false
    add_electronic_check_flag: false
    add_paperless_echeck_flag: false
    add_price_pressure_ratio: false

  preprocessing:
    Scaler:
      type: 
        'standard'
      params: 
        with_mean = false

  geo:
    strategy:
      drop
  

