data:
  raw_path: data/raw/Telco_customer_churn.xlsx
  target: Churn Value
  test_size: 0.3
  random_state: 42
  drop_cols:
  - Country
  - State
  - Lat Long
  - Churn Label
  - Churn Reason
  - Count
  meta_cols:
  - CLTV
  - CustomerID
features:
  engineering:
    drop_churn_score: false
    add_engagement_score: true
    add_tenure_group: true
    add_tenure_log: true
    add_contract_ordinal: true
    add_family_stability: true
    add_fiber_no_support: true
    add_support_gap_count: true
    add_payment_automatic_flag: true
    add_electronic_check_flag: true
    add_paperless_echeck_flag: true
    add_price_pressure_ratio: true
  geo:
    strategy: drop
preprocessing:
  scaler:
    type: standard
    params:
      with_mean: false
model:
  name: xgboost
  params:
    objective: binary:logistic
    eval_metric: logloss
    random_state: 42
    n_jobs: 1
    n_estimators: 250
    max_depth: 4
    learning_rate: 0.0290126075096391
    min_child_weight: 1
    subsample: 1.0
    colsample_bytree: 0.9
    gamma: 0.6
    reg_alpha: 0.5
    reg_lambda: 3.428007642179676
    scale_pos_weight: 2.7691131498470947
cv:
  type: stratified_kfold
  n_splits: 5
  shuffle: true
  random_state: 42
  n_jobs: 1
  scoring:
    pr_auc: average_precision
    roc_auc: roc_auc
    recall: recall
    precision: precision
    f1_score: f1
tracking:
  experiment_name: evaluation-xgb
  tracking_uri: sqlite:///mlflow.db
tuning:
  primary_metric: pr_auc
  direction: maximize
  n_trials: 25
  timeout_seconds: 1800
  convergence_patience_trials: 50
  convergence_min_improvement: 0.005
  search_space:
    n_estimators:
    - 200
    - 250
    - 300
    max_depth:
      low: 3
      high: 5
      step: 1
    learning_rate:
      low: 0.01
      high: 0.03
      log: true
    min_child_weight:
      low: 1
      high: 3
      step: 1
    subsample:
      low: 0.5
      high: 1.0
      step: 0.1
    colsample_bytree:
      low: 0.5
      high: 1.0
      step: 0.1
    gamma:
      low: 0.0
      high: 0.6
      step: 0.2
    reg_alpha:
      low: 0.0
      high: 0.5
      step: 0.1
    reg_lambda:
      low: 2
      high: 10.0
      log: true
evaluation:
  threshold: 0.5
  activation_cost: 50.0
  retention_rate: 0.1
optuna_result:
  source_config: config\experiments\optuna_xgb.yaml
  primary_metric: pr_auc
  best_metrics:
    pr_auc_mean: 0.9602764732332381
    pr_auc_std: 0.00881343042151914
    roc_auc_mean: 0.9843232339320227
    roc_auc_std: 0.0033873178566566236
    recall_mean: 0.9533502968617473
    recall_std: 0.021871163885900713
    precision_mean: 0.8046867407992455
    precision_std: 0.005969370177251077
    f1_score_mean: 0.8725403211419875
    f1_score_std: 0.006416253985039575
    fit_time_mean: 0.12383785247802734
    score_time_mean: 0.02426939010620117
  best_trial_number: 10
